name = "aetherst-license-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "aetherst-licenses"
database_id = "fa47f1c1-e920-4979-b0a0-14957764702d"

[vars]
ADMIN_TOKEN = "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET"
